name: Send reminder

on:
  workflow_dispatch:
  schedule:
    - cron: "0 10,15 * * mon-fri"

jobs:
  send-reminder:
    name: Send reminder
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install deps
        run: npm install
      - name: Send reminder
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        run: npm run do-it
